### ISSUE TITLE
binary UnstructuredGrid is incomplete under ifort

### ISSUE THREAD

**Issue by RBCanelas** [szaghi/VTKFortran#24]
Hello!

Have been using this lib for a few weeks to output particles in an unstructured mesh (would be great to have polydata, I have no idea how difficult it would be to contribute). 

When passing large-ish arrays (~30k reals?), I get a stack overflow under ifort. Using /heap-arrays does nothing as it seems to be a assignment on the fly copy issue. Using /nostandard-realloc-lhs there is no stack overflow but there is problem with the files if written in binary, as most fields are left empty.

I'll try to provide a more complete picture, until then, any gut feelings as to how that might be?

Regards

**Comment by szaghi** [comment]
Hi, thanks for the feedback.

Polydata has never been considered due to my needs (and no other users asked for it), thus I cannot say how difficult it is, I'll try to investigate it soon.

The large-array issue is interesting: with raw (binary) file there could be issues, but in writing speed rather in stack-related problems... this is very interesting, if you can send a reproducible test I'll investigate rapidly to fix the issue.

Thank you again.

**Comment by RBCanelas** [comment]
Hey,

since, for my needs, I can write particle data in an unstructured mesh format with blank fields, it's not a problem. Shame that on paraview I then need to use gaussian sprites instead of just points, this will be bad when I get to 10^6 particles...

I'm able to reproduce the behavior with your write_vtu.f90 on my windows system (and since this seems to run fine on my unix system, I'm guessing the problem is going to be interesting to find...)

ifort -O3 -heap-arrays -nostandard-realloc-lhs

ascii and raw work properly, binary leaves some fields empty, but the xml is proper. for now I'm using raw, so don't loose sleep over this.

You are the one to thank. Your libraries are pure gold for poor fortran people, and have allowed me to do months of work in a few days, you are my fortran hero.

Cheers!

**Comment by szaghi** [comment]
Hi @RBCanelas 

> I'm able to reproduce the behavior with your write_vtu.f90 on my windows system (and since this seems to run fine on my unix system, I'm guessing the problem is going to be interesting to find...)

Yes, it is interesting the different behavior of the two OS, but I am not a Windows users (and I do not want to became one of them :smile: ), maybe is it related to the different handling of stack/heap memory?

> ifort -O3 -heap-arrays -nostandard-realloc-lhs

Why do you use `-nostandard-realloc-lhs`? I should use only standard Fortran feature, the left-hand-side is automatically reallocated only if needed in F03/08. Are you using an older Fortran compiler? Currently I am using GCC 8 and Ifort 2018.

> ascii and raw work properly, binary leaves some fields empty, but the xml is proper. for now I'm using raw, so don't loose sleep over this.

This is really interesting: binary, in the VTK world, is base64 format and I use another of my library to convert Fortran binary (really binary :smile: ) data to base64 ascii code. Probably, the bug is in that library, BeFor64, that could be *stressed* in converting a lot of data (GB?) in an ascii (base64) code. Under your GNU Linux, binary (base64) are files correctly generated?

If there is no rush, I'll try to investigate later this month.

Thank you again.
